[package]
name = "cloud-file-signer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { version = "1.35.0", features = ["full"] }
async-trait = "0.1.74"
time = { version = "0.3.30", features = ["local-offset"] }
aws-sdk-s3 = "1.5.0"
azure_core = "0.17.0"
azure_storage = "0.17.0"
azure_storage_blobs = "0.17.0"

[dev-dependencies]
